version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
    

  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: main 
      MYSQL_USER: mysql_rot
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33066:3306

volumes:
  dbdata:
